USE my_db;

CREATE TABLE IF NOT EXISTS aerolineas(
	ID_AEROLINEA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_AEROLINEA VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS aeropuertos(
	ID_AEROPUERTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_AEROPUERTO VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS movimientos(
	ID_MOVIMIENTOS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS vuelos(
	ID_VUELOS INT AUTO_INCREMENT PRIMARY KEY,
	ID_AEROLINEA INT,
    ID_AEROPUERTO INT,
    ID_MOVIMIENTO INT,
    DIA DATE
);


